name: manso_fa

channels:
  - conda-forge

dependencies:
  - python=3.10

  # core estable
  - numpy
  - pandas
  - scipy

  # geospatial (flexible)
  - geopandas
  - rasterio
  - rioxarray
  - xarray
  - gdal
  - shapely
  - pyproj
  - proj
  - proj-data

  # plotting
  - matplotlib
  - seaborn

  # utils
  - tqdm
  - python-dateutil