
# -*- coding: utf-8 -*-
"""
Plot timeseries at flowline level and for the entire glacier. 
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.ticker import ScalarFormatter
from datetime import datetime
from pathlib import Path



# Load results from CSV files (generated by FA_subseasonal.py)
df_flow = pd.read_csv('output/subseasonal/flowlines_results.csv', parse_dates=['Start_Date', 'End_Date'])
df_FA = pd.read_csv('output/subseasonal/frontal_ablation_results.csv', parse_dates=['Start', 'End'])


df_FA['upper'] = df_FA['Frontal_ablation_m3d'] + df_FA['Err_Frontal_ablation']
df_FA['lower'] = df_FA['Frontal_ablation_m3d'] - df_FA['Err_Frontal_ablation']



palette_sur = sns.blend_palette(["lightgreen", "darkgreen"], n_colors=5)
palette_centro = sns.blend_palette(["lightcoral", "red", "lightcoral"], n_colors=5)
palette_centro[2] = "darkred"
palette_norte = sns.blend_palette(["lightblue", "blue"], n_colors=5)[::-1]
paleta_completa = palette_sur + palette_centro + palette_norte


fig, axs = plt.subplots(5, 1, sharex=True, figsize=(12, 15))

start_date = datetime(2017, 1, 30)
end_date = datetime(2024, 5, 1)

# Flowline variables 
variables = ["Ut", "dL/dt", "Uc", "Ht"]
y_labels = ["$U_{T}$ (m d$^{-1}$)", "dL/dt (m d$^{-1}$)", 
            "$\\dot{a}$ (m d$^{-1}$)", "H (m)", "FA (m$^{3}$ d$^{-1}$)"]

y_lims = [(0.1, 0.5), (-2, 1), (0, 2), (0, 100), None]

for i, var in enumerate(variables):
    ax = axs[i]
    ax.set_xlim(start_date, end_date)
    
    for _, row in df_flow.iterrows():
        color = paleta_completa[row['ID'] - 1]
        ax.hlines(y=row[var], xmin=row['Start_Date'], xmax=row['End_Date'],
                  color=color, linewidth=3)
    
    if y_lims[i]:
        ax.set_ylim(y_lims[i])
        
    ax.set_ylabel(y_labels[i], fontsize=20)
    ax.tick_params(axis='y', labelsize=17)
    
    for year in range(2017, 2025):
        ax.axvline(x=datetime(year, 12, 31), color='k', linestyle='dashed', 
                   linewidth=1, alpha=0.5)
    
    if i < 4:
        ax.xaxis.set_visible(False)

# Frontal ablation 
ax = axs[4]

for _, row in df_FA.iterrows():
    ax.plot([row['Start'], row['End']], 
            [row['Frontal_ablation_m3d'], row['Frontal_ablation_m3d']],
            color='black', linewidth=2)
    ax.fill_between([row['Start'], row['End']], 
                    [row['lower'], row['lower']], 
                    [row['upper'], row['upper']],
                    color='gray', alpha=0.4)

ax.set_xlim(start_date, end_date)
ax.set_ylim(0,40000)
ax.set_yticks([0, 10000,20000,30000,40000])

# Scientific notation 
formatter = ScalarFormatter(useMathText=True)
formatter.set_powerlimits((3, 3))
ax.yaxis.set_major_formatter(formatter)
ax.ticklabel_format(axis='y', style='sci', scilimits=(3, 3))
ax.yaxis.get_offset_text().set_size(16)
ax.set_ylabel(y_labels[4], fontsize=20)
ax.tick_params(axis='y', labelsize=17)

for year in range(2017, 2025):
    ax.axvline(datetime(year, 12, 31), color='k', ls='dashed', lw=1, alpha=0.5)

# X-axis configuration
axs[4].xaxis.set_minor_locator(mdates.MonthLocator([4, 8, 12]))
axs[4].xaxis.set_minor_formatter(mdates.DateFormatter('%b'))
axs[4].xaxis.set_major_locator(mdates.YearLocator())
axs[4].xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
axs[4].tick_params(axis='x', which='major', labelsize=18, pad=18)
axs[4].tick_params(axis='x', which='minor', labelsize=14)

plt.subplots_adjust(hspace=0)

# Legends
sur_ids = [1, 2, 3, 4, 5]
centro_ids = [6, 7, 8, 9, 10]
norte_ids = [11, 12, 13, 14, 15]

color_dict = {i+1: paleta_completa[i] for i in range(len(paleta_completa))}
present_ids = df_flow['ID'].unique()

legend_sur = [plt.Line2D([0], [0], color=color_dict[id_], lw=3, label=f"ID {id_:02d}")
              for id_ in sur_ids if id_ in present_ids]
legend_centro = [plt.Line2D([0], [0], color=color_dict[id_], lw=3, label=f"ID {id_:02d}")
                 for id_ in centro_ids if id_ in present_ids]
legend_norte = [plt.Line2D([0], [0], color=color_dict[id_], lw=3, label=f"ID {id_:02d}")
                for id_ in norte_ids if id_ in present_ids]

if legend_sur:
    fig.legend(handles=legend_sur, loc='upper right', bbox_to_anchor=(1.1, 0.99),
               title='South', fontsize=14, title_fontsize=16)
if legend_centro:
    fig.legend(handles=legend_centro, loc='upper right', bbox_to_anchor=(1.1, 0.795),
               title='Center', fontsize=14, title_fontsize=16)
if legend_norte:
    fig.legend(handles=legend_norte, loc='upper right', bbox_to_anchor=(1.1, 0.6025),
               title='North', fontsize=14, title_fontsize=16)

plt.tight_layout()
plt.show()